### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by Azel-ytof** [kornelski/xml-rs#32]
Hi,

First of all, thank you for your work, it is really usefull !

Here's my problem :
I've an app in production that was in 0.8.4 without any problem.
Then I've run a cargo update and I get the 0.8.24, and I've now encoding problems.
So because I do not use you directly (I use serde-xml-rs that use you), I have to find where does the bug come from.
After some research, sorry, it's `xml-rs`.

So here the texte with right encoding that I get with 0.8.4:
```Canal Saint-Martin - Quai de Jemmapes\nEn exclusivité, découvrez ce superbe appartement familial situé au 2e étage avec ascenseur d'une copropriété des années 90. \nCe bien rare se compose : d'une entrée, d'un double séjour lumineux (34,7 m²) avec un petit balcon offrant une vue dégagée sur le Canal Saint-Martin, d'une cuisine américaine équipée séparée ouvrant sur un second balcon, d'une suite parentale avec salle d'eau, WC et dressing, d'une seconde chambre avec dressing, d'une salle de bain et WC indépendant. Les chambres, situées côté jardin, bénéficient d'un calme absolu.\nL'appartement présente un beau potentiel, avec la possibilité d'aménager une troisième chambre. Situé dans un emplacement prisé du 10e arrondissement, ce bien d'exception saura vous séduire par son charme et son cadre idéal.\n\nEn supplément : une place de parking est également disponible.\nCopropriété de 35 lots (Pas de procédure en cours). \n\r Charges annuelles : 3693  euros.\n Julie Garziano (EI) Agent Commercial - Numéro RSAC : 879499663 - Nanterre.```

Now here's the same text in 0.8.24 :
```Canal Saint-Martin - Quai de Jemmapes\nEn exclusivitÃ©, dÃ©couvrez ce superbe appartement familial situÃ© au 2e Ã©tage avec ascenseur d'une copropriÃ©tÃ© des annÃ©es 90. \nCe bien rare se compose : d'une entrÃ©e, d'un double sÃ©jour lumineux (34,7 mÂ²) avec un petit balcon offrant une vue dÃ©gagÃ©e sur le Canal Saint-Martin, d'une cuisine amÃ©ricaine Ã©quipÃ©e sÃ©parÃ©e ouvrant sur un second balcon, d'une suite parentale avec salle d'eau, WC et dressing, d'une seconde chambre avec dressing, d'une salle de bain et WC indÃ©pendant. Les chambres, situÃ©es cÃ´tÃ© jardin, bÃ©nÃ©ficient d'un calme absolu.\nL'appartement prÃ©sente un beau potentiel, avec la possibilitÃ© d'amÃ©nager une troisiÃ¨me chambre. SituÃ© dans un emplacement prisÃ© du 10e arrondissement, ce bien d'exception saura vous sÃ©duire par son charme et son cadre idÃ©al.\n\nEn supplÃ©ment : une place de parking est Ã©galement disponible.\nCopropriÃ©tÃ© de 35 lots (Pas de procÃ©dure en cours). \n\r Charges annuelles : 3693  euros.\n Julie Garziano (EI) Agent Commercial - NumÃ©ro RSAC : 879499663 - Nanterre.```

Here are my search steps :

- 0.8.9 : `Error while parsing Ac3 XML from string : Syntax: 1756:27 Invalid char`

- 0.8.10 : `Error while parsing Ac3 XML from string : Syntax: 1756:27 Invalid character U+0089`

- 0.8.12 : `thread 'main' panicked at C:\Users\tony0\.cargo\registry\src\index.crates.io-6f17d22bba15001f\xml-rs-0.8.12\src\reader\parser.rs:411:9:
How did you get a document that weird? Please file a bug`

- 0.8.14 : `thread 'main' panicked at C:\Users\tony0\.cargo\registry\src\index.crates.io-6f17d22bba15001f\xml-rs-0.8.14\src\reader\parser\outside_tag.rs:100:26:
You've found a bug in xml-rs, caused by calls to push_pos() in states that don't end up emitting events.
            This case is ignored in release mode, and merely causes document positions to be out of sync.
            Please file a bug and include the XML document that triggers this assert.`

- 0.8.16 : text with encoding problems

Please note that I extract file content the `encoding_rs` crate to get the string already encoded
So do you insert e bug, or does I misundesrtand how this crate works ?

Thank you in advance for your help

**Comment by kornelski** [comment]
If you've been changing encoding using encoding_rs, it's possible that you haven't updated `<?xml encoding>` prolog, and the encoding conversion is now performed twice — once by you using encoding_rs, and the second time by the new xml-rs version.

Make sure that the bytes in the document match the encoding it declares.

**Comment by kornelski** [comment]
Remove the `<?xml … ?>` line from the start of the file. 

If this directive says the file must be interpreted as latin1 or some non-UTF-8 code page, but you've converted the file to UTF-8, then you've broken the file. You need to remove the outdated encoding information.

There's no option for this in xml-rs, because I would prefer not to implement a workaround for every bug somebody has in their XML files.

**Comment by Azel-ytof** [comment]
The problem is that I don't create this type of XML.
I simply receive XML from my customers' products, and they're not going to change their code just because they don't respect XML best practices (in fact, they already don't respect their own documentation...).

I understand that you do not want to implement workaround, but that's a regression from an older version.
And this is not a bug in the XML... It is not mandatory anymore, but it can be still used...

**Comment by kornelski** [comment]
The prolog can easily be removed with a regex or even a simple check of the first few characters of the first line. 
You already have a pipeline that adds encoding_rs, so you can add removal of XML prolog too. 
It's a very simple change. You don't need to parse it, you don't need to update it. Just delete the outdated line after the encoding conversion.

**Comment by Azel-ytof** [comment]
Hi, thank you for your explanation :)

Indeed, removing the prolog before parsing works !

But I don't understand why you say that the prolog is outdated, I've never heard something about that
